# Generated by Django 4.2.2 on 2023-06-18 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0002_remove_sensor_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurement',
            name='updated_at',
        ),
    ]
